version: '3.3'

services:
  web:
    image: nginx:latest # nginx 이미지
    container_name: web # 컨테이너 명
    restart: "on-failure" # 구동 실패 시 재시작
    ports:
      - 80:80
    volumes: # 볼륨 설정
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html