version : '3.1'

services:
  mysql:
    image: mysql
    restart: always
    container_name: ct-db-mysql
    ports:
      - "3307:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: admin
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql

