version: '3.4'

services:
  mysql:
      platform: linux/x86_64
      image: mysql
      restart: always
      container_name: ct-db-mysql
      ports:
        - "3307:3306"
      environment: 
        MYSQL_ROOT_PASSWORD: admin
      command: 
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - ./db/data:/var/lib/mysql

  web:
    image: nginx:latest # nginx 이미지
    container_name: web # 컨테이너 명
    restart: "on-failure" # 구동 실패 시 재시작
    ports:
      - 80:80
    volumes: # 볼륨 설정
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
 
  server-a:
    build: # Dockerfile 빌드
      context: . # Dockerfile 빌드 경로
    container_name: server-A # 컨테이너 명
    restart: "on-failure"
    # expose:
    #   - 5000 # 도커 내부적 포트
    #   - 5001
    ports:
      - 5000:5000
    volumes: # 볼륨 설정
      - './server:/app'
      - '/app/node_modules'
    environment: # 환경변수 설정
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CONTAINER_NAME=serverA
    stdin_open: true
    tty: true

  server-b:
    build: # Dockerfile 빌드
      context: . # Dockerfile 빌드 경로
    container_name: server-B # 컨테이너 명
    restart: "on-failure"
    # expose:
    #   - 5000 # 도커 내부적 포트
    #   - 5001
    ports:
      - 5001:5000
    volumes: # 볼륨 설정
      - './server:/app'
      - '/app/node_modules'
    environment: # 환경변수 설정
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CONTAINER_NAME=serverB
    stdin_open: true
    tty: true

  server-c:
    build: # Dockerfile 빌드
      context: . # Dockerfile 빌드 경로
    container_name: server-C # 컨테이너 명
    restart: "on-failure"
    # expose:
    #   - 5000 # 도커 내부적 포트
    #   - 5001
    ports:
      - 5002:5000
    volumes: # 볼륨 설정
      - './server:/app'
      - '/app/node_modules'
    environment: # 환경변수 설정
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CONTAINER_NAME=serverC
    stdin_open: true
    tty: true

  # server-d:
  #   build: # Dockerfile 빌드
  #     context: . # Dockerfile 빌드 경로
  #   container_name: server-D # 컨테이너 명
  #   restart: "on-failure"
  #   # expose:
  #   #   - 5000 # 도커 내부적 포트
  #   #   - 5001
  #   ports:
  #     - 5003:5000
  #   volumes: # 볼륨 설정
  #     - './server:/app'
  #     - '/app/node_modules'
  #   environment: # 환경변수 설정
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #     - CONTAINER_NAME=serverD
  #   stdin_open: true
  #   tty: true